export const questions = [
  'How do you handle tight deadlines when multiple projects require your attention simultaneously?',
  'Describe a situation where you had to explain a complex technical concept to a non-technical stakeholder.',
  'Tell me about a time when you received critical feedback on your code. How did you respond?',
  'How do you approach disagreements with team members about technical decisions?',
  'Describe your experience working in agile development environments.',
  'How do you prioritize tasks when everything seems urgent?',
  'Tell me about a time when you had to learn a new technology quickly to complete a project.',
  'How do you handle situations where requirements change midway through a project?',
  'Describe a situation where you demonstrated leadership within a development team.',
  'How do you maintain work-life balance during intensive development cycles?',
  'Tell me about a time when you made a significant mistake. How did you handle it?',
  'How do you approach mentoring junior developers?',
  'Describe your communication style when working with remote team members.',
  'How do you stay updated with the latest technologies and development practices?',
  'Tell me about a time when you had to push back on a feature request. How did you handle it?',
  "How do you handle situations where you don't know the answer to a problem?",
  'Describe a situation where you had to collaborate with designers to implement a user interface.',
  "How do you approach code reviews, both when reviewing others' code and receiving feedback on yours?",
  'Tell me about a time when you had to make a decision with incomplete information.',
  'How do you handle conflicts within a development team?',
  'Describe your approach to documentation and knowledge sharing.',
  'How do you manage stress during critical production issues or system outages?',
  'Tell me about a time when you had to advocate for better development practices or tools.',
  'How do you communicate project delays or technical challenges to project managers or clients?',
  'Describe a situation where you had to adapt to a completely different tech stack or development environment.',
  'How do you balance quality with speed when developing features?',
  'Tell me about a time when you had to work with difficult team members or stakeholders.',
  'How do you approach giving constructive feedback to peers?',
  'Describe your experience working cross-functionally with product managers, designers, and other stakeholders.',
  'How do you handle situations where you strongly disagree with a decision made by management?',
];
